# Notebook für die Daten Transformation und laden in data/silver

## Imports

In [186]:
import pandas as pd
import requests
from tqdm import tqdm
import os
from datetime import datetime, timedelta

## load data from data/bronze

In [187]:
lfa1 = pd.read_csv("/workspace/data/bronze/LFA1.csv", sep=";")
rechnungen_sap_2023 = pd.read_csv("/workspace/data/bronze/Rechnungen_SAP_2023.csv", sep=";")
rechnungen_sap_2024 = pd.read_csv("/workspace/data/bronze/Rechnungen_SAP_2024.csv", sep="|")

data_dict = {
    "LFA1": lfa1,
    "Rechnungen_SAP_2023": rechnungen_sap_2023,
    "Rechnungen_SAP_2024": rechnungen_sap_2024
}

## Ausgabe der ersten Zeilen

In [188]:
pd.set_option('display.max_columns', None)  # Show all columns in the output
pd.set_option('display.max_rows', None)  # Show all rows in the output

In [189]:
for i in data_dict.keys():
    print(f"Data from {i}:")
    print("Anzahl Spalten:", data_dict[i].shape[1], "Anzahl Zeilen:", data_dict[i].shape[0])
    display(data_dict[i].head())
    print("\n")

Data from LFA1:
Anzahl Spalten: 2 Anzahl Zeilen: 68252

  Lieferant                         Name
0     L0194   Deutsche Post GmbH & Co.KG
1     L0027                 ROBERT BOSCH
2     L0097        Engelbert und Strauss
3     L0028   Maschinenbau GmbH & Co. KG
4     L0028   Maschinenbau GmbH & Co. KG

Data from Rechnungen_SAP_2023:
Anzahl Spalten: 22 Anzahl Zeilen: 34170

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag
0,R-81402060,NaN,2023-01-01,Versand Kundenprämien,L0194,SK_000008,Porto und Brief,2,Vertriebsgesellschaft GmbH,NaN,NaN,14020000,1,NaN,NaN,683.40,EUR,14,14 Tage netto,2023-01-15,2023-01-09,NaN
1,R-60983007,NaN,2023-01-01,Zylinderschraube DIN,L0027,SK_000003,Maschinenteile und Ersatzte.,1,Produktion Bonn GmbH,NaN,NaN,23110000,1,NaN,NaN,211.53,EUR,30,30 Tage netto,2023-01-31,2023-02-10,V-74154614
2,R-51330234,NaN,2023-01-01,Dummy Klaus Ludwig Leopard-Sicherheitsschuhe T...,L0097,SK_000004,"Arbeitssicherheit, Ausr.",2,Vertriebsgesellschaft GmbH,NaN,NaN,40250703,1,NaN,NaN,8655.51,EUR,30,30 Tage; 1% Skonto,2023-01-31,2023-01-25,NaN
3,R-62280354,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10937.30,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-11,NaN
4,R-21995158,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10991.05,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-29,NaN

Data from Rechnungen_SAP_2024:
Anzahl Spalten: 22 Anzahl Zeilen: 34082

,Rechnungsnummer_SAP,Bestellnummer,BelegDatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Rechnungswert,Rechnungswährung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag
0,R-19934029,NaN,01/01/2024,Papier weiß A3,L0318,SK_000002,NaN,3,Verwaltung Demo AG,NaN,NaN,24260604,1,NaN,NaN,1217.95,USD,30,30 Tage; 1% Skonto,2024-01-31,2024-01-28,NaN
1,R-20408868,NaN,01/01/2024,Zylinderschraube,L0028,NaN,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,23110000,1,NaN,NaN,592.38,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-02-11,NaN
2,R-53946015,NaN,01/01/2024,Zylinderschraube DIN,L0028,NaN,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,23110000,1,NaN,NaN,419.30,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-01-09,NaN
3,R-49696293,NaN,01/01/2024,"Test Runddrahtbürsten Ø x-mm Edelstdr. gew.,mm...",L0028,NaN,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,21190605,1,NaN,NaN,2804.05,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-01-09,NaN
4,R-45623784,NaN,01/01/2024,Gas Pauschale September,L0315,SK_000020,NaN,4,Auslandsgesellschaft SRO,NaN,NaN,26040201,1,NaN,NaN,34259.35,USD,30,30 Tage netto,2024-01-31,2024-01-26,V-27993028

In [190]:
# Ausgabe der dtypes
for i in data_dict.keys():
    print(f"Data from {i}:")
    display(data_dict[i].dtypes)
    print("\n")

Data from LFA1:

Lieferant    object
Name         object
dtype: object

Data from Rechnungen_SAP_2023:

Rechnungsnummer          object
Bestellnummer            object
Belegdatum               object
Beschreibung             object
Lieferant_Nummer         object
Sachkonto-Nummer         object
Sachkonto-Name           object
Buchungskreis-Nummer      int64
Buchungskreis-Name       object
Material-Nummer          object
Material-Name            object
ECLASS-identifier         int64
Menge                     int64
Mengeneinheit            object
Stückpreis              float64
Spend                   float64
Währung                  object
Zahlungsziel-Tage         int64
Zahlungsbedingung        object
Zahlungsfrist            object
Zahlungsdatum            object
Rahmenvertrag            object
dtype: object

Data from Rechnungen_SAP_2024:

Rechnungsnummer_SAP      object
Bestellnummer            object
BelegDatum               object
Beschreibung             object
Lieferant_Nummer         object
Sachkonto-Nummer         object
Sachkonto-Name           object
Buchungskreis-Nummer      int64
Buchungskreis-Name       object
Material-Nummer          object
Material-Name            object
ECLASS-identifier         int64
Menge                     int64
Mengeneinheit            object
Stückpreis              float64
Rechnungswert           float64
Rechnungswährung         object
Zahlungsziel-Tage         int64
Zahlungsbedingung        object
Zahlungsfrist            object
Zahlungsdatum            object
Rahmenvertrag            object
dtype: object

# Genauere Blick auf LFA1

In [191]:
# wie viele unique Lieferanten gibt es
print(f"Anzahl Unique Lieferanten: {lfa1['Lieferant'].nunique()}")

lieferanten = lfa1.groupby("Lieferant")
# Ausgabe von groupby("Lieferant")
for i, (name, group) in enumerate(lieferanten):
    print(f"\nGruppe: {name}")
    display(group.head()) 
    if i == 4:
        break

Anzahl Unique Lieferanten: 219

Gruppe: L0003

     Lieferant                Name
380      L0003   TATA STEEL EUROPE
940      L0003   TATA STEEL EUROPE
1243     L0003   TATA STEEL EUROPE
2516     L0003   TATA STEEL EUROPE
2517     L0003   TATA STEEL EUROPE

Gruppe: L0005

    Lieferant                      Name
72      L0005   Krupp Essen Deutschland
76      L0005   Krupp Essen Deutschland
154     L0005   Krupp Essen Deutschland
225     L0005   Krupp Essen Deutschland
230     L0005   Krupp Essen Deutschland

Gruppe: L0006

     Lieferant                  Name
413      L0006   KRUPP ESSEN GERMANY
640      L0006   KRUPP ESSEN GERMANY
700      L0006   KRUPP ESSEN GERMANY
1829     L0006   KRUPP ESSEN GERMANY
2967     L0006   KRUPP ESSEN GERMANY

Gruppe: L0007

    Lieferant               Name
166     L0007   Krupp Essen GmbH
214     L0007   Krupp Essen GmbH
226     L0007   Krupp Essen GmbH
366     L0007   Krupp Essen GmbH
401     L0007   Krupp Essen GmbH

Gruppe: L0008

    Lieferant          Name
66      L0008   Krupp+Essen
67      L0008   Krupp+Essen
82      L0008   Krupp+Essen
152     L0008   Krupp+Essen
367     L0008   Krupp+Essen

### Prüfen ob alle Name in Lieferant gleich sind

In [192]:
# prüfen ob alle Name in Lieferant gleich sind

# Gruppen prüfen, bei denen nicht nur ein eindeutiger Name vorkommt
inkonsistente = []

for lieferant_id, group in lieferanten:
    unique_names = group["Name"].unique()
    print(f"Lieferant {lieferant_id} hat {len(unique_names)} eindeutige Namen.")
    if len(unique_names) > 1:
        inkonsistente.append((lieferant_id, unique_names))

# Ergebnis anzeigen
if inkonsistente:
    for lieferant_id, names in inkonsistente:
        print(f"Lieferant {lieferant_id} hat mehrere Namen: {names}")
else:
    print("Es gibt keine inkonsistenten Lieferanten.")

Lieferant L0003 hat 1 eindeutige Namen.
Lieferant L0005 hat 1 eindeutige Namen.
Lieferant L0006 hat 1 eindeutige Namen.
Lieferant L0007 hat 1 eindeutige Namen.
Lieferant L0008 hat 1 eindeutige Namen.
Lieferant L0009 hat 1 eindeutige Namen.
Lieferant L0012 hat 1 eindeutige Namen.
Lieferant L0023 hat 1 eindeutige Namen.
Lieferant L0026 hat 1 eindeutige Namen.
Lieferant L0027 hat 1 eindeutige Namen.
Lieferant L0028 hat 1 eindeutige Namen.
Lieferant L0029 hat 1 eindeutige Namen.
Lieferant L0030 hat 1 eindeutige Namen.
Lieferant L0031 hat 1 eindeutige Namen.
Lieferant L0032 hat 1 eindeutige Namen.
Lieferant L0033 hat 1 eindeutige Namen.
Lieferant L0034 hat 1 eindeutige Namen.
Lieferant L0035 hat 1 eindeutige Namen.
Lieferant L0036 hat 1 eindeutige Namen.
Lieferant L0037 hat 1 eindeutige Namen.
Lieferant L0038 hat 1 eindeutige Namen.
Lieferant L0039 hat 1 eindeutige Namen.
Lieferant L0040 hat 1 eindeutige Namen.
Lieferant L0041 hat 1 eindeutige Namen.
Lieferant L0042 hat 1 eindeutige Namen.
Lieferant L0043 hat 1 eindeutige Namen.
Lieferant L0044 hat 1 eindeutige Namen.
Lieferant L0045 hat 1 eindeutige Namen.
Lieferant L0046 hat 1 eindeutige Namen.
Lieferant L0047 hat 1 eindeutige Namen.
Lieferant L0048 hat 1 eindeutige Namen.
Lieferant L0049 hat 1 eindeutige Namen.
Lieferant L0050 hat 1 eindeutige Namen.
Lieferant L0051 hat 1 eindeutige Namen.
Lieferant L0052 hat 1 eindeutige Namen.
Lieferant L0053 hat 1 eindeutige Namen.
Lieferant L0054 hat 1 eindeutige Namen.
Lieferant L0055 hat 1 eindeutige Namen.
Lieferant L0056 hat 1 eindeutige Namen.
Lieferant L0057 hat 1 eindeutige Namen.
Lieferant L0058 hat 1 eindeutige Namen.
Lieferant L0059 hat 1 eindeutige Namen.
Lieferant L0060 hat 1 eindeutige Namen.
Lieferant L0061 hat 1 eindeutige Namen.
Lieferant L0062 hat 1 eindeutige Namen.
Lieferant L0063 hat 1 eindeutige Namen.
Lieferant L0064 hat 1 eindeutige Namen.
Lieferant L0065 hat 1 eindeutige Namen.
Lieferant L0066 hat 1 eindeutige Namen.
Lieferant L0067 hat 1 eindeutige Namen.
Lieferant L0068 hat 1 eindeutige Namen.
Lieferant L0069 hat 1 eindeutige Namen.
Lieferant L0070 hat 1 eindeutige Namen.
Lieferant L0071 hat 1 eindeutige Namen.
Lieferant L0072 hat 1 eindeutige Namen.
Lieferant L0073 hat 1 eindeutige Namen.
Lieferant L0074 hat 1 eindeutige Namen.
Lieferant L0075 hat 1 eindeutige Namen.
Lieferant L0076 hat 1 eindeutige Namen.
Lieferant L0079 hat 1 eindeutige Namen.
Lieferant L0081 hat 1 eindeutige Namen.
Lieferant L0082 hat 1 eindeutige Namen.
Lieferant L0083 hat 1 eindeutige Namen.
Lieferant L0084 hat 1 eindeutige Namen.
Lieferant L0085 hat 1 eindeutige Namen.
Lieferant L0087 hat 1 eindeutige Namen.
Lieferant L0093 hat 1 eindeutige Namen.
Lieferant L0095 hat 1 eindeutige Namen.
Lieferant L0097 hat 1 eindeutige Namen.
Lieferant L0098 hat 1 eindeutige Namen.
Lieferant L0099 hat 1 eindeutige Namen.
Lieferant L0100 hat 1 eindeutige Namen.
Lieferant L0101 hat 1 eindeutige Namen.
Lieferant L0102 hat 1 eindeutige Namen.
Lieferant L0103 hat 1 eindeutige Namen.
Lieferant L0104 hat 1 eindeutige Namen.
Lieferant L0105 hat 1 eindeutige Namen.
Lieferant L0106 hat 1 eindeutige Namen.
Lieferant L0107 hat 1 eindeutige Namen.
Lieferant L0108 hat 1 eindeutige Namen.
Lieferant L0109 hat 1 eindeutige Namen.
Lieferant L0110 hat 1 eindeutige Namen.
Lieferant L0111 hat 1 eindeutige Namen.
Lieferant L0112 hat 1 eindeutige Namen.
Lieferant L0113 hat 1 eindeutige Namen.
Lieferant L0114 hat 1 eindeutige Namen.
Lieferant L0115 hat 1 eindeutige Namen.
Lieferant L0117 hat 1 eindeutige Namen.
Lieferant L0118 hat 1 eindeutige Namen.
Lieferant L0119 hat 1 eindeutige Namen.
Lieferant L0120 hat 1 eindeutige Namen.
Lieferant L0121 hat 1 eindeutige Namen.
Lieferant L0122 hat 1 eindeutige Namen.
Lieferant L0123 hat 1 eindeutige Namen.
Lieferant L0125 hat 1 eindeutige Namen.
Lieferant L0126 hat 1 eindeutige Namen.
Lieferant L0127 hat 1 eindeutige Namen.
Lieferant L0128 hat 1 eindeutige Namen.
Lieferant L0129 hat 1 eindeutige Namen.
Lieferant L0130 hat 1 eindeutige Namen.
Lieferant L0131 hat 1 eindeutige Namen.
Lieferant L0132 hat 1 eindeutige Namen.
Lieferant L0133 hat 1 eindeutige Namen.
Lieferant L0134 hat 1 eindeutige Namen.
Lieferant L0136 hat 1 eindeutige Namen.
Lieferant L0137 hat 1 eindeutige Namen.
Lieferant L0138 hat 1 eindeutige Namen.
Lieferant L0139 hat 1 eindeutige Namen.
Lieferant L0140 hat 1 eindeutige Namen.
Lieferant L0141 hat 1 eindeutige Namen.
Lieferant L0142 hat 1 eindeutige Namen.
Lieferant L0144 hat 1 eindeutige Namen.
Lieferant L0146 hat 1 eindeutige Namen.
Lieferant L0148 hat 1 eindeutige Namen.
Lieferant L0150 hat 1 eindeutige Namen.
Lieferant L0153 hat 1 eindeutige Namen.
Lieferant L0155 hat 1 eindeutige Namen.
Lieferant L0156 hat 1 eindeutige Namen.
Lieferant L0157 hat 1 eindeutige Namen.
Lieferant L0161 hat 1 eindeutige Namen.
Lieferant L0162 hat 1 eindeutige Namen.
Lieferant L0163 hat 1 eindeutige Namen.
Lieferant L0164 hat 1 eindeutige Namen.
Lieferant L0165 hat 1 eindeutige Namen.
Lieferant L0166 hat 1 eindeutige Namen.
Lieferant L0167 hat 1 eindeutige Namen.
Lieferant L0168 hat 1 eindeutige Namen.
Lieferant L0169 hat 1 eindeutige Namen.
Lieferant L0170 hat 1 eindeutige Namen.
Lieferant L0171 hat 1 eindeutige Namen.
Lieferant L0174 hat 1 eindeutige Namen.
Lieferant L0178 hat 1 eindeutige Namen.
Lieferant L0180 hat 1 eindeutige Namen.
Lieferant L0181 hat 1 eindeutige Namen.
Lieferant L0184 hat 1 eindeutige Namen.
Lieferant L0187 hat 1 eindeutige Namen.
Lieferant L0189 hat 1 eindeutige Namen.
Lieferant L0190 hat 1 eindeutige Namen.
Lieferant L0191 hat 1 eindeutige Namen.
Lieferant L0192 hat 1 eindeutige Namen.
Lieferant L0193 hat 1 eindeutige Namen.
Lieferant L0194 hat 1 eindeutige Namen.
Lieferant L0195 hat 1 eindeutige Namen.
Lieferant L0196 hat 1 eindeutige Namen.
Lieferant L0197 hat 1 eindeutige Namen.
Lieferant L0198 hat 1 eindeutige Namen.
Lieferant L0199 hat 1 eindeutige Namen.
Lieferant L0200 hat 1 eindeutige Namen.
Lieferant L0201 hat 1 eindeutige Namen.
Lieferant L0202 hat 1 eindeutige Namen.
Lieferant L0203 hat 1 eindeutige Namen.
Lieferant L0204 hat 1 eindeutige Namen.
Lieferant L0207 hat 1 eindeutige Namen.
Lieferant L0208 hat 1 eindeutige Namen.
Lieferant L0209 hat 1 eindeutige Namen.
Lieferant L0210 hat 1 eindeutige Namen.
Lieferant L0211 hat 1 eindeutige Namen.
Lieferant L0212 hat 1 eindeutige Namen.
Lieferant L0213 hat 1 eindeutige Namen.
Lieferant L0214 hat 1 eindeutige Namen.
Lieferant L0216 hat 1 eindeutige Namen.
Lieferant L0217 hat 1 eindeutige Namen.
Lieferant L0218 hat 1 eindeutige Namen.
Lieferant L0219 hat 1 eindeutige Namen.
Lieferant L0220 hat 1 eindeutige Namen.
Lieferant L0221 hat 1 eindeutige Namen.
Lieferant L0222 hat 1 eindeutige Namen.
Lieferant L0223 hat 1 eindeutige Namen.
Lieferant L0225 hat 1 eindeutige Namen.
Lieferant L0230 hat 1 eindeutige Namen.
Lieferant L0231 hat 1 eindeutige Namen.
Lieferant L0232 hat 1 eindeutige Namen.
Lieferant L0233 hat 1 eindeutige Namen.
Lieferant L0234 hat 1 eindeutige Namen.
Lieferant L0235 hat 1 eindeutige Namen.
Lieferant L0236 hat 1 eindeutige Namen.
Lieferant L0237 hat 1 eindeutige Namen.
Lieferant L0238 hat 1 eindeutige Namen.
Lieferant L0239 hat 1 eindeutige Namen.
Lieferant L0241 hat 1 eindeutige Namen.
Lieferant L0242 hat 1 eindeutige Namen.
Lieferant L0243 hat 1 eindeutige Namen.
Lieferant L0244 hat 1 eindeutige Namen.
Lieferant L0245 hat 1 eindeutige Namen.
Lieferant L0246 hat 1 eindeutige Namen.
Lieferant L0249 hat 1 eindeutige Namen.
Lieferant L0254 hat 1 eindeutige Namen.
Lieferant L0257 hat 1 eindeutige Namen.
Lieferant L0258 hat 1 eindeutige Namen.
Lieferant L0259 hat 1 eindeutige Namen.
Lieferant L0260 hat 1 eindeutige Namen.
Lieferant L0261 hat 1 eindeutige Namen.
Lieferant L0262 hat 1 eindeutige Namen.
Lieferant L0264 hat 1 eindeutige Namen.
Lieferant L0275 hat 1 eindeutige Namen.
Lieferant L0280 hat 1 eindeutige Namen.
Lieferant L0281 hat 1 eindeutige Namen.
Lieferant L0282 hat 1 eindeutige Namen.
Lieferant L0283 hat 1 eindeutige Namen.
Lieferant L0284 hat 1 eindeutige Namen.
Lieferant L0293 hat 1 eindeutige Namen.
Lieferant L0294 hat 1 eindeutige Namen.
Lieferant L0295 hat 1 eindeutige Namen.
Lieferant L0298 hat 1 eindeutige Namen.
Lieferant L0301 hat 1 eindeutige Namen.
Lieferant L0302 hat 1 eindeutige Namen.
Lieferant L0303 hat 1 eindeutige Namen.
Lieferant L0304 hat 1 eindeutige Namen.
Lieferant L0305 hat 1 eindeutige Namen.
Lieferant L0315 hat 1 eindeutige Namen.
Lieferant L0316 hat 1 eindeutige Namen.
Lieferant L0317 hat 1 eindeutige Namen.
Lieferant L0318 hat 1 eindeutige Namen.
Lieferant L0322 hat 1 eindeutige Namen.
Lieferant L0323 hat 1 eindeutige Namen.
Lieferant L0324 hat 1 eindeutige Namen.
Lieferant L0325 hat 1 eindeutige Namen.
Lieferant L0326 hat 1 eindeutige Namen.
Lieferant L0327 hat 1 eindeutige Namen.
Es gibt keine inkonsistenten Lieferanten.

### Drop duplizierte Lieferanten

In [193]:
def drop_duplicates_lieferanten(df: pd.DataFrame) -> pd.DataFrame:
    """
    Entfernt duplizierte Lieferanten basierend auf den Spalten 'Lieferant' und 'Name'.

    Args:
        df (pd.DataFrame): Der DataFrame, aus dem Duplikate entfernt werden sollen.

    Returns:
        pd.DataFrame: Ein DataFrame ohne duplizierte Lieferanten.
    """
    return df.drop_duplicates(subset=["Lieferant", "Name"], keep='first').reset_index(drop=True)

In [194]:
lfa1_cleaned = drop_duplicates_lieferanten(lfa1)

In [195]:
display(lfa1_cleaned)

    Lieferant                                      Name
0       L0194                Deutsche Post GmbH & Co.KG
1       L0027                              ROBERT BOSCH
2       L0097                     Engelbert und Strauss
3       L0028                Maschinenbau GmbH & Co. KG
4       L0193                       Deutsche Post  GmbH
5       L0026                         Robert Bosch GmbH
6       L0190                          Deutsche Post AG
7       L0192                     Deutsche Post Germany
8       L0031                              Heinrichs AG
9       L0063                Lämmermeier Edelstahl GmbH
10      L0069                                     Rexel
11      L0169                        Stölting Reinigung
12      L0161                      Reinigung Fassbender
13      L0189                             Deutsche Post
14      L0236       Vereinigte Papierwarenfabriken GmbH
15      L0142                              Securitas AB
16      L0216                    IN-TIME Transport GmbH
17      L0029                Maschinentechnik Bonn GmbH
18      L0052             Gebr. Kniffruth GmbH & Co. KG
19      L0138                 Braam Gebäudedienste GmbH
20      L0316                   Stadtwerke Köln Öl GmbH
21      L0198                      Hermes international
22      L0008                               Krupp+Essen
23      L0318                          Wasserleasing AG
24      L0005                   Krupp Essen Deutschland
25      L0195                               Hapag-Lloyd
26      L0283                 Consultants International
27      L0071                            IFM Elektronic
28      L0056           Wilhelm Modersohn GmbH & Co. KG
29      L0315                      Stadtwerke Bonn GmbH
30      L0204                    Zustelldienst Mut GmbH
31      L0041                       Göcke GmbH & Co. KG
32      L0099                      Lerner International
33      L0317           Schreibwarenladen "um die Ecke"
34      L0191                             DEUTSCHE POST
35      L0302                                  Europcar
36      L0235                           Poste Nationale
37      L0141                 Gebäudedienste Bernd e.K.
38      L0074        BEDIA Motorentechnik GmbH & Co. KG
39      L0007                          Krupp Essen GmbH
40      L0098                        UVEX Arbeitsschutz
41      L0036                        RADOLID Thiel GmbH
42      L0196                                       UPS
43      L0260                       Telekom Deutschland
44      L0199                                 Hermes AG
45      L0042         Kieselbach Maschinenbauteile GmbH
46      L0171                                  Stölting
47      L0242                                     Adobe
48      L0259                      Telekom (Schweiz) AG
49      L0032                               Honecker KG
50      L0241                             Adobe Limited
51      L0162                     Reinigung Schulz e.K.
52      L0039                        Moser Handels GmbH
53      L0067               Sonepar D./Region West GmbH
54      L0136                 Facility Specialists GmbH
55      L0117                 Christ Arbeitsschutz GmbH
56      L0003                         TATA STEEL EUROPE
57      L0280                           Consultec Spain
58      L0070               Honeywell Process Solutions
59      L0006                       KRUPP ESSEN GERMANY
60      L0060                 Worrings Prüftechnik GmbH
61      L0304                            Cyberport GmbH
62      L0066                               cadout GmbH
63      L0222                       Kita Logistics GmbH
64      L0037                                  Metawell
65      L0140                                GaLaBau AG
66      L0040                   Böhler Einbauteile GmbH
67      L0033                  Toyota Motor Corporation
68      L0261                            TELEKOM FRANCE
69      L0061                       Christian Zang GmbH
70      L0303                 Mercateo Deutschland GmbH
71      L0293                  AIM Unternehmensberatung
72      L0325                 ERP Service End2End Corp.
73      L0257                                   TELEKOM
74      L0034       Schmelting Verbindungselemente GmbH
75      L0197                                    Hermes
76      L0053                 Kleo-Werke Bielefeld GmbH
77      L0054                           Maler-Berlen AG
78      L0035               A. Dreckshage GmbH & Co. KG
79      L0294                                BuLaCon AG
80      L0102                Berufskleider-Leasing GmbH
81      L0068                       Sonepar Deutschland
82      L0202                        Kurierdienst Maier
83      L0207    Lorenz Klaholz Transport GmbH & Co. KG
84      L0209        ABELE Spedition und Transport GmbH
85      L0073                     PEAK electronics GmbH
86      L0128                    BIG Arbeitsschutz GmbH
87      L0065                        Gummitechnik Civak
88      L0327                              Adecco Group
89      L0064     Quiter Metall- und Armaturenwerk GmbH
90      L0139                       Gebäude Wimmer GmbH
91      L0232                         Spedition West AG
92      L0051                       Klaas und Cie. GmbH
93      L0243                      SAP Deutschland GmbH
94      L0275                                 Consultec
95      L0295                       Tennfield & Partner
96      L0322        Tech Softwaredienstleistungen GmbH
97      L0157                                  Remondis
98      L0050                  Schneider Drehteile GmbH
99      L0155                         Projektteam FM AG
100     L0030           Würth Vertriebsgesellschaft mbH
101     L0281                       Management Services
102     L0045   TORLOPP Industrie- und Messtechnik GmbH
103     L0101                          Karl Schelm GmbH
104     L0113              ERT - E. Richard THIEME GmbH
105     L0217         Karl Heinz Dietrich GmbH & Co. KG
106     L0121           masterdress Berufskleidung GmbH
107     L0120                WIWOX GmbH Surface Systems
108     L0137                   WISAG Facility Services
109     L0062              Carl Stahl Technocables GmbH
110     L0284            Management Consulting Partners
111     L0126                      WEICON GmbH & Co. KG
112     L0203                      Kurztransporte Balau
113     L0258                              Telekom GmbH
114     L0323               ERP Service End 2 End Corp.
115     L0324                       ERP SERVICE END2END
116     L0163                          Tänzer-Reinigung
117     L0249                          HighTechSoftware
118     L0201                       Kurierdienst Müller
119     L0043                         Ernst Thomas GmbH
120     L0156               Vovenius Umweltservice GmbH
121     L0079              Arthur Behrens GmbH & Co. KG
122     L0211                     Hintzen Logistik GmbH
123     L0044          Ferdinand Bilstein GmbH + Co. KG
124     L0262             Huawei Technologies Co., Ltd.
125     L0012               Lelger Metallkomponenten SE
126     L0166                            Kandi Pro GmbH
127     L0210                        ALGO Logistik GmbH
128     L0220              Latzer Global Logistics GmbH
129     L0049                                 MoHa GmbH
130     L0059                  Gema Central Europe GmbH
131     L0326                 ERP Service End-End Corp.
132     L0046                              FRANKSA GmbH
133     L0131                                     JUTEC
134     L0057                            microball GmbH
135     L0180                               Facil-Clean
136     L0237                          Deutsche Post AG
137     L0245                                  SAP SARL
138     L0047                         Basedo Steel GmbH
139     L0009                                BLRT Grupp
140     L0234                     Transporte de Espagna
141     L0084                               Kohsel GmbH
142     L0038                   Karl Späh GmbH & Co. KG
143     L0058               TER Chemicals GmbH & Co. KG
144     L0081                        WERAP Wicklerei AG
145     L0112                    DaVinci SMARTWEAR GmbH
146     L0075                          Lieckipedia GmbH
147     L0264                                  MobilCom
148     L0167                            Kandi-Pro GmbH
149     L0133                               Möwius GmbH
150     L0134                                 Nägele AG
151     L0072                                     Rexel
152     L0170                             Stölting GmbH
153     L0239                             Dederichs GbR
154     L0130                      Ledertechnik Köln AG
155     L0305                            Amazon s.a.r.l
156     L0083            ICS SCHNEIDER MESSTECHNIK GmbH
157     L0164                 Reinigungsteam Blitzblank
158     L0168                    Kalko Pascal Reinigung
159     L0023     Ernst Metallwarenfabrik GmbH & Co. KG
160     L0219                                 Hess GmbH
161     L0153           Hageman & Kümmerer GmbH & Co.KG
162     L0231                        Spedition Ost GmbH
163     L0100                           B2B Hygieneshop
164     L0208                 SCHERBAUER SPEDITION GmbH
165     L0129                         Gebr. Flunde GmbH
166     L0110                     Burgia Sauerland GmbH
167     L0085               MRC Components GmbH & Co.KG
168     L0103                         Dress for Work eG
169     L0218                                DACHSER SE
170     L0119                Industriebedarf eusan GmbH
171     L0282                    Management Services AG
172     L0108                             priwotec GmbH
173     L0106               KONSTANT Arbeitsschutz GmbH
174     L0165                  Industrie-Säuberung Matt
175     L0125                   Salzmann Restwaren GmbH
176     L0174                  Reinigungsservice Müller
177     L0230                             Panaria Cargo
178     L0233                     Transeuropa Transport
179     L0132               Knitter Schutzkleidung GmbH
180     L0221                 Spedition Bernhard Peters
181     L0104              Friedrich Münch GmbH & Co KG
182     L0122                          JEM Medical GmbH
183     L0238                          Packungsexperten
184     L0187                     Saubere Leistung GmbH
185     L0200                               Hermes GmbH
186     L0105          Scheibler Importgesellschaft mbH
187     L0246                               ByTech GmbH
188     L0150                              Evalfacility
189     L0048                       Speth GmbH & Co. KG
190     L0127              WABOTECH Befestigungstechnik
191     L0181                 Fassadenreinigung Schmidt
192     L0184                           Clean-Team GmbH
193     L0223                       GO Logistik-Service
194     L0123                        WERO GmbH & Co. KG
195     L0212                    Probst Speditions GmbH
196     L0148           DWII Gebäudeinstandhaltung Gmbh
197     L0146                    Condamus International
198     L0114                      Leipold + Döhle GmbH
199     L0178                           MILO Facilities
200     L0214                              Brugger GmbH
201     L0144                               WIS Technik
202     L0244                                    SAP SE
203     L0118                                DECON GmbH
204     L0115       Warschow Technischer Großhandel OHG
205     L0254                 TaskForce Management Soft
206     L0111                      Diebold & Streich KG
207     L0213                       Erb Transporte GmbH
208     L0055            Malori Produktionstechnik GmbH
209     L0298                  ConversionConsultants SE
210     L0107                        Wilhelm Klein GmbH
211     L0082                                   MP GmbH
212     L0109               WIROS Wilfried Rosbach GmbH
213     L0093                           Hans Turck & Co
214     L0087              Analog Microelectronics GmbH
215     L0095                                     Natus
216     L0301                     Autohaus Störtebecker
217     L0225                          Transporte Meier
218     L0076                  Weidmüller GmbH & Co. KG

# Genauere Blick auf SAP Rechnungen 2023

In [196]:
# gibt es fehlende Werte in den Lieferantendaten
display(rechnungen_sap_2023.isna().sum())

Rechnungsnummer             0
Bestellnummer           28208
Belegdatum                  0
Beschreibung                0
Lieferant_Nummer            0
Sachkonto-Nummer            0
Sachkonto-Name              0
Buchungskreis-Nummer        0
Buchungskreis-Name          0
Material-Nummer         28208
Material-Name           28208
ECLASS-identifier           0
Menge                       0
Mengeneinheit           28208
Stückpreis              28208
Spend                       0
Währung                     0
Zahlungsziel-Tage           0
Zahlungsbedingung           0
Zahlungsfrist               0
Zahlungsdatum               0
Rahmenvertrag           27275
dtype: int64

### Merge lieferantenname

In [197]:

def merge_lieferanten_names(df: pd.DataFrame, lfa1_df: pd.DataFrame) -> pd.DataFrame:
    """
    Merge Lieferanten-Namen aus dem LFA1 DataFrame in das Rechnungen DataFrame.

    Args:
        df (pd.DataFrame): Das Rechnungen DataFrame, in das die Namen eingefügt werden sollen.
        lfa1_df (pd.DataFrame): Das LFA1 DataFrame, das die Lieferantennamen enthält.

    Returns:
        pd.DataFrame: Ein DataFrame mit den Lieferantennamen aus dem LFA1 DataFrame.
    """
    return df.merge(lfa1_df[['Lieferant', 'Name']], left_on='Lieferant_Nummer', right_on='Lieferant', how='left').drop(columns='Lieferant')

In [198]:
rechnungen_sap_2023_lieferantenname = merge_lieferanten_names(rechnungen_sap_2023, lfa1_cleaned).rename(columns={'Name': 'Lieferantenname'})

In [199]:
for i, (name, group) in enumerate(rechnungen_sap_2023_lieferantenname.groupby("Lieferant_Nummer")):
    print(f"\nGruppe: {name}")
    display(group.head(1))
    if i == 4:
        break

Gruppe: L0003

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
380,R-72788362,B-88391834,2023-01-04,Stahl legiert wellbl. IDL737 500,L0003,SK_000001,Wareneinkauf,2,Vertriebsgesellschaft GmbH,M-016,Stahl legiert wellbl. IDL737 500,35060105,174,Rolle,850.0,147900.0,EUR,180,180 Tage netto,2023-07-03,2023-08-01,NaN,TATA STEEL EUROPE

Gruppe: L0005

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
72,R-10981168,B-44879492,2023-01-01,Draht Max 0-15,L0005,SK_000001,Wareneinkauf,5,US plant Inc.,M-017,Draht Max 0-15,35060601,156,Meter,80.0,12480.0,EUR,60,60 Tage netto,2023-03-02,2023-03-01,NaN,Krupp Essen Deutschland

Gruppe: L0006

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
413,R-00347148,B-51842853,2023-01-05,Stahl legiert wellbl. IDL737 500,L0006,SK_000001,Wareneinkauf,3,Verwaltung Demo AG,M-016,Stahl legiert wellbl. IDL737 500,35060105,261,Rolle,850.0,221850.0,EUR,14,14 Tage netto,2023-01-19,2023-02-17,V-34844011,KRUPP ESSEN GERMANY

Gruppe: L0007

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
166,R-85753889,B-26534037,2023-01-02,Draht CT8 SF 0-10,L0007,SK_000001,Wareneinkauf,5,US plant Inc.,M-021,Draht CT8 SF 0-10,35060601,258,Meter,65.0,16770.0,EUR,180,180 Tage netto,2023-07-01,2023-06-28,V-11169730,Krupp Essen GmbH

Gruppe: L0008

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
66,R-35114858,B-26998748,2023-01-01,Draht CT8 SF 0-10,L0008,SK_000001,Wareneinkauf,4,Auslandsgesellschaft SRO,M-021,Draht CT8 SF 0-10,35060601,103,Meter,65.0,6695.0,USD,0,Sofort ohne Abzug,2023-01-01,2021-12-27,V-81587600,Krupp+Essen

### Überprüfen wie viele unterschiedliche Währungen es gibt

In [200]:

display(rechnungen_sap_2023['Währung'].unique())
display(rechnungen_sap_2024['Rechnungswährung'].unique())

for währung in rechnungen_sap_2023['Währung'].unique():
    print(f"Währung: {währung}")
    display(rechnungen_sap_2023[rechnungen_sap_2023['Währung'] == währung].head())

array(['EUR', 'USD', 'GBP'], dtype=object)

array(['USD', 'EUR', 'GBP'], dtype=object)

Währung: EUR

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag
0,R-81402060,NaN,2023-01-01,Versand Kundenprämien,L0194,SK_000008,Porto und Brief,2,Vertriebsgesellschaft GmbH,NaN,NaN,14020000,1,NaN,NaN,683.40,EUR,14,14 Tage netto,2023-01-15,2023-01-09,NaN
1,R-60983007,NaN,2023-01-01,Zylinderschraube DIN,L0027,SK_000003,Maschinenteile und Ersatzte.,1,Produktion Bonn GmbH,NaN,NaN,23110000,1,NaN,NaN,211.53,EUR,30,30 Tage netto,2023-01-31,2023-02-10,V-74154614
2,R-51330234,NaN,2023-01-01,Dummy Klaus Ludwig Leopard-Sicherheitsschuhe T...,L0097,SK_000004,"Arbeitssicherheit, Ausr.",2,Vertriebsgesellschaft GmbH,NaN,NaN,40250703,1,NaN,NaN,8655.51,EUR,30,30 Tage; 1% Skonto,2023-01-31,2023-01-25,NaN
3,R-62280354,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10937.30,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-11,NaN
4,R-21995158,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10991.05,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-29,NaN

Währung: USD

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag
15,R-43006533,NaN,2023-01-01,Dichtung 18.97162,L0027,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,23070000,1,NaN,NaN,447.15,USD,30,30 Tage netto,2023-01-31,2023-01-28,V-81636418
16,R-05660076,NaN,2023-01-01,Zylinderschraube DIN,L0028,SK_000003,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,23110000,1,NaN,NaN,496.65,USD,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-11,NaN
17,R-19838123,NaN,2023-01-01,Reinigung Büro in Bonn,L0169,SK_000022,Reinigungsdienstleistung,2,Vertriebsgesellschaft GmbH,NaN,NaN,25290100,1,NaN,NaN,62207.79,USD,30,30 Tage; 1% Skonto,2023-01-31,2023-01-29,NaN
18,R-28385022,NaN,2023-01-01,Reinigung Bürogebäude in Bonn - Q1,L0161,SK_000022,Reinigungsdienstleistung,4,Auslandsgesellschaft SRO,NaN,NaN,25290100,1,NaN,NaN,84586.12,USD,0,Sofort ohne Abzug,2023-01-01,2021-12-31,NaN
19,R-63273934,NaN,2023-01-01,Schlitzschraubenzieher,L0026,SK_000003,Maschinenteile und Ersatzte.,5,US plant Inc.,NaN,NaN,21040490,1,NaN,NaN,551.20,USD,14,14 Tage netto,2023-01-15,2023-01-14,NaN

Währung: GBP

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag
15742,R-68266911,NaN,2023-06-18,Bu1 ZINKEIMER LITER,L0236,SK_000009,Logistik,1,Produktion Bonn GmbH,NaN,NaN,20050101,1,NaN,NaN,1453.75,GBP,14,14 Tage netto,2023-07-02,2023-07-04,NaN
16055,R-59091440,NaN,2023-06-21,Papier A3 120g /m² weiß Inkjet 100Bl/Pg,L0318,SK_000030,Bürobedarf,1,Produktion Bonn GmbH,NaN,NaN,24260604,1,NaN,NaN,789.27,GBP,30,30 Tage; 1% Skonto,2023-07-21,2023-07-15,NaN
16056,R-34217140,B-77649583,2023-06-21,DIN 933 A4-70 M 16x50 ISO 4017 Sechskantschrauben,L0026,SK_000003,Maschinenteile und Ersatzte.,5,US plant Inc.,M-004,DIN 933 A4-70 M 16x50 ISO 4017 Sechskantschrauben,23110115,125,Stück,3.0,375.00,GBP,14,14 Tage netto,2023-07-05,2023-07-18,NaN
16057,R-35388948,NaN,2023-06-21,Schraubendreher mit Bits,L0028,SK_000003,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,21040490,1,NaN,NaN,401.89,GBP,14,"14 Tage; 1,5% Skonto",2023-07-05,2023-07-02,NaN
16058,R-12664095,NaN,2023-06-21,Schraubendreher mit Bits,L0028,SK_000003,Maschinenteile und Ersatzte.,2,Vertriebsgesellschaft GmbH,NaN,NaN,21040490,1,NaN,NaN,887.55,GBP,14,"14 Tage; 1,5% Skonto",2023-07-05,2023-07-03,NaN

### Bauen eines Wechselkurs df

In [201]:

def get_exchange_rates_df(start_date: str, end_date: str) -> pd.DataFrame:
    """
    Holt Wechselkurse von USD und GBP zu EUR für jeden Tag im angegebenen Zeitraum.
    
    Parameter:
    - start_date (str): Startdatum im Format "YYYY-MM-DD"
    - end_date (str): Enddatum im Format "YYYY-MM-DD"
    
    Rückgabe:
    - DataFrame mit Spalten: Datum, Wechselkurs_USD, Wechselkurs_GBP
    """
    start_date  = datetime.strptime(start_date, "%Y-%m-%d")
    end_date  = datetime.strptime(end_date, "%Y-%m-%d")
    
    data = []

    # Tagesweise iterieren
    current_date = start_date
    while current_date <= end_date:
        formatted_date = current_date.strftime("%Y-%m-%d")
        
        usd_rate, gbp_rate = None, None

        # USD → EUR
        resp_usd = requests.get(f"https://api.frankfurter.app/{formatted_date}?from=USD&to=EUR")
        if resp_usd.ok:
            usd_rate = resp_usd.json()["rates"]["EUR"]

        # GBP → EUR
        resp_gbp = requests.get(f"https://api.frankfurter.app/{formatted_date}?from=GBP&to=EUR")
        if resp_gbp.ok:
            gbp_rate = resp_gbp.json()["rates"]["EUR"]
        
        data.append({
            "Datum": formatted_date,
            "Wechselkurs_USD": usd_rate,
            "Wechselkurs_GBP": gbp_rate
        })
        
        current_date += timedelta(days=1)

        df = pd.DataFrame(data)

        if df.isnull().values.any():
            print(f"Fehlende Wechselkurse für das Datum: {formatted_date}")

    return df

In [ ]:
wechselkurse_df = get_exchange_rates_df("2023-01-01", "2024-12-31")
wechselkurse_df.head()

In [ ]:
wechselkurse_df.to_csv("/workspace/data/wechselkurse.csv", index=False, sep=";")

In [ ]:
wechselkurse_df = pd.read_csv("/workspace/data/silver/wechselkurse.csv", sep=";")

In [ ]:
wechselkurse_df.isna().sum()

Datum              0
Wechselkurs_USD    0
Wechselkurs_GBP    0
dtype: int64

### Inplausible Daten gefunden, es gibt Daten indem das Belegdatum später ist als das Zahlungsdatum und das Rechnungen von 2023 im Jahr 2021 bezahlt wurden. Es sieht als wären die Zahlungsdatum von 2021 um ein Jahr nach hinten geschoben sind also eigentlich vom Jahr 2022. Das wäre zu klären mit ein Domänexperte. Für den weiteren Verlauf werden die Rechnungen vom Jahr 2021 gelöscht.

In [ ]:
fehlerhafte_zeilen = rechnungen_sap_2023_lieferantenname[
    rechnungen_sap_2023_lieferantenname["Zahlungsdatum"] < rechnungen_sap_2023_lieferantenname["Belegdatum"]
]

display(fehlerhafte_zeilen[["Zahlungsdatum", "Belegdatum", "Lieferant_Nummer", "Lieferantenname", "Spend"]].sort_values(by="Zahlungsdatum").head(10))
print(f"Anzahl 'fehlerhafter' Zeilen: {len(fehlerhafte_zeilen)}")

    Zahlungsdatum  Belegdatum Lieferant_Nummer       Lieferantenname     Spend
67     2021-12-26  2023-01-01            L0008           Krupp+Essen  11635.00
66     2021-12-27  2023-01-01            L0008           Krupp+Essen   6695.00
5      2021-12-28  2023-01-01            L0193   Deutsche Post  GmbH   1154.69
152    2021-12-28  2023-01-02            L0008           Krupp+Essen  10335.00
283    2021-12-28  2023-01-03            L0193   Deutsche Post  GmbH   1943.13
20     2021-12-29  2023-01-01            L0189         Deutsche Post   1388.20
107    2021-12-29  2023-01-02            L0193   Deutsche Post  GmbH   1153.91
248    2021-12-29  2023-01-03            L0193   Deutsche Post  GmbH    733.82
170    2021-12-30  2023-01-02            L0071        IFM Elektronic  22718.81
428    2021-12-30  2023-01-05            L0193   Deutsche Post  GmbH   1795.05

Anzahl 'fehlerhafter' Zeilen: 2124

In [ ]:
# drop Zeilen mit Zahlungsdatum < 2022
def drop_invalid_payments(df: pd.DataFrame, min_date: str) -> pd.DataFrame:
    """
    Entfernt Zeilen mit einem Zahlungsdatum vor dem angegebenen Mindestdatum.

    Args:
        df (pd.DataFrame): Das DataFrame, aus dem die ungültigen Zahlungen entfernt werden sollen.
        min_date (str): Das Mindestdatum im Format 'YYYY-MM-DD'.

    Returns:
        pd.DataFrame: Ein DataFrame ohne ungültige Zahlungen.
    """

    return df[df["Zahlungsdatum"] >= min_date]

In [ ]:
rechnungen_sap_2023_lieferantenname_valid = drop_invalid_payments(rechnungen_sap_2023_lieferantenname, "2022-01-01")

In [ ]:
display(rechnungen_sap_2023_lieferantenname_valid[["Zahlungsdatum", "Belegdatum", "Lieferant_Nummer", "Lieferantenname", "Spend", "Währung"]].sort_values(by="Zahlungsdatum").head())

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung
423,2023-01-01,2023-01-05,L0060,Worrings Prüftechnik GmbH,605.85,EUR
426,2023-01-01,2023-01-05,L0161,Reinigung Fassbender,7855.90,EUR
430,2023-01-01,2023-01-05,L0193,Deutsche Post GmbH,862.46,EUR
449,2023-01-01,2023-01-05,L0189,Deutsche Post,1178.29,EUR
499,2023-01-01,2023-01-06,L0189,Deutsche Post,898.55,EUR

### Wechselkurs den Rechnungen Df hinzufügen

In [ ]:
def add_wechselkurse_to_rechnungen(rechnungen_df: pd.DataFrame, wechselkurse_df: pd.DataFrame, währung_column: str, zahlungsdatum_column: str) -> pd.DataFrame:
    """
    Fügt Wechselkurse zu den Rechnungsdaten hinzu.
    
    Args:
    - rechnungen_df (pd.DataFrame): DataFrame mit Rechnungsdaten
    - wechselkurse_df (pd.DataFrame): DataFrame mit Wechselkursen
    - währung_column (str): Der Name der Währungsspalte im Rechnungs-DataFrame
    - zahlungsdatum_column (str): Der Name der Zahlungsdatumsspalte im Rechnungs-DataFrame

    Returns:
    - pd.DataFrame: DataFrame mit hinzugefügten Wechselkursen
    """
    wechselkurs_liste = []

    for _, row in rechnungen_df.iterrows():
        datum = row[zahlungsdatum_column]
        währung = row[währung_column]

        if pd.isna(datum) or pd.isna(währung):
            print("Daten fehlen")
            break

        if währung == "EUR":
            wechselkurs_liste.append(1.0)
        else:
            kurs_row = wechselkurse_df[wechselkurse_df["Datum"] == datum]
            if kurs_row.empty:
                wechselkurs_liste.append(None)
            else:
                if währung == "USD":
                    wechselkurs_liste.append(kurs_row["Wechselkurs_USD"].values[0])
                elif währung == "GBP":
                    wechselkurs_liste.append(kurs_row["Wechselkurs_GBP"].values[0])
                else:
                    wechselkurs_liste.append(None)

    rechnungen_df["Wechselkurs"] = wechselkurs_liste

    return rechnungen_df

In [ ]:
rechnungen_sap_2023_lieferantenname_valid_wechselkurs = add_wechselkurse_to_rechnungen(rechnungen_sap_2023_lieferantenname_valid, wechselkurse_df, "Währung", "Zahlungsdatum")

/tmp/ipykernel_1149/2556523556.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rechnungen_df["Wechselkurs"] = wechselkurs_liste

In [ ]:
for i, (name, group) in enumerate(rechnungen_sap_2023_lieferantenname_valid_wechselkurs.groupby("Währung")):
    print(f"\nGruppe: {name}")
    display(group[["Zahlungsdatum", "Belegdatum", "Lieferant_Nummer", "Lieferantenname", "Spend", "Währung", "Wechselkurs"]].head(1))
    if i == 4:
        break

Gruppe: EUR

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs
0,2023-01-09,2023-01-01,L0194,Deutsche Post GmbH & Co.KG,683.4,EUR,1.0

Gruppe: GBP

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs
15742,2023-07-04,2023-06-18,L0236,Vereinigte Papierwarenfabriken GmbH,1453.75,GBP,1.1672

Gruppe: USD

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs
15,2023-01-28,2023-01-01,L0027,ROBERT BOSCH,447.15,USD,0.92039

In [ ]:
display(wechselkurse_df[wechselkurse_df["Datum"] == "2023-07-04"])
display(wechselkurse_df[wechselkurse_df["Datum"] == "2023-01-28"])

          Datum  Wechselkurs_USD  Wechselkurs_GBP
184  2023-07-04          0.91785           1.1672

         Datum  Wechselkurs_USD  Wechselkurs_GBP
27  2023-01-28          0.92039           1.1379

### Alle Rechnungen in Euro rechnen

In [ ]:
def calc_spendeuro(rechnungen_df: pd.DataFrame, spend_column: str) -> pd.DataFrame:
    """
    Berechnet den Betrag in Euro für jede Zeile basierend auf der Währung und dem Wechselkurs.

    Args:
        rechnungen_df (pd.DataFrame): Das DataFrame, das die Spalten 'Spend', 'Wechselkurs' enthält.
        spend_column (str): Der Name der Spalte, die den Betrag in der ursprünglichen Währung enthält.

    Returns:
        pd.DataFrame: Ein DataFrame mit einer neuen Spalte 'Spend_EUR'
    """
    rechnungen_df["Spend_EUR"] = rechnungen_df[spend_column] * rechnungen_df["Wechselkurs"]

    return rechnungen_df

In [ ]:
rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro = calc_spendeuro(rechnungen_sap_2023_lieferantenname_valid_wechselkurs, "Spend")

/tmp/ipykernel_1149/1806863438.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rechnungen_df["Spend_EUR"] = rechnungen_df[spend_column] * rechnungen_df["Wechselkurs"]

In [ ]:
for i, (name, group) in enumerate(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro.groupby("Währung")):
    print(f"\nGruppe: {name}")
    display(group[["Zahlungsdatum", "Belegdatum", "Lieferant_Nummer", "Lieferantenname", "Spend", "Währung", "Wechselkurs", "Spend_EUR"]].head(1))
    if i == 4:
        break

Gruppe: EUR

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs,Spend_EUR
0,2023-01-09,2023-01-01,L0194,Deutsche Post GmbH & Co.KG,683.4,EUR,1.0,683.4

Gruppe: GBP

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs,Spend_EUR
15742,2023-07-04,2023-06-18,L0236,Vereinigte Papierwarenfabriken GmbH,1453.75,GBP,1.1672,1696.817

Gruppe: USD

,Zahlungsdatum,Belegdatum,Lieferant_Nummer,Lieferantenname,Spend,Währung,Wechselkurs,Spend_EUR
15,2023-01-28,2023-01-01,L0027,ROBERT BOSCH,447.15,USD,0.92039,411.552389

### Überprüfen der Sachkonto- nummer und name

In [ ]:
print(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro["Sachkonto-Nummer"].unique())
print(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro[["Sachkonto-Nummer", "Sachkonto-Name"]].drop_duplicates())

['SK_000008' 'SK_000003' 'SK_000004' 'SK_000009' 'SK_000022' 'SK_000007'
 'SK_000005' 'SK_000020' 'SK_000002' 'SK_000001' 'SK_000030' 'SK_000014'
 'SK_000015' 'SK_000029' 'SK_000019' 'SK_000011' 'SK_000016' 'SK_000021'
 'SK_000013']
     Sachkonto-Nummer                         Sachkonto-Name
0           SK_000008                        Porto und Brief
1           SK_000003           Maschinenteile und Ersatzte.
2           SK_000004               Arbeitssicherheit, Ausr.
7           SK_000009                               Logistik
17          SK_000022               Reinigungsdienstleistung
21          SK_000007                         Logistikbedarf
25          SK_000005               Aufwendungen für Gebäude
55          SK_000020                                Energie
69          SK_000002  Verrechnung vorherige Buchungsperiode
72          SK_000001                           Wareneinkauf
78          SK_000030                             Bürobedarf
131         SK_000014                             KFZ-Kosten
185         SK_000015                       Dienstleistungen
234         SK_000029                               Lizenzen
400         SK_000019                    Beratungsleistungen
556         SK_000011                 Arbeitsmittel Hardware
750         SK_000016                   Mediendienstleistung
1657        SK_000021            Aufwendungen für Entsorgung
3335        SK_000013                   Außendienst Hardware

In [ ]:
print(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro["Sachkonto-Name"].unique())

['Porto und Brief' 'Maschinenteile und Ersatzte.'
 'Arbeitssicherheit, Ausr.' 'Logistik' 'Reinigungsdienstleistung'
 'Logistikbedarf' 'Aufwendungen für Gebäude' 'Energie'
 'Verrechnung vorherige Buchungsperiode' 'Wareneinkauf' 'Bürobedarf'
 'KFZ-Kosten' 'Dienstleistungen' 'Lizenzen' 'Beratungsleistungen'
 'Arbeitsmittel Hardware' 'Mediendienstleistung'
 'Aufwendungen für Entsorgung' 'Außendienst Hardware']

### Überprüfen des Belegdatum

In [ ]:
print(rechnungen_sap_2023["Belegdatum"].unique())

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31' '2023-02-01' '2023-02-02' '2023-02-03' '2023-02-04'
 '2023-02-05' '2023-02-06' '2023-02-07' '2023-02-08' '2023-02-09'
 '2023-02-10' '2023-02-11' '2023-02-12' '2023-02-13' '2023-02-14'
 '2023-02-15' '2023-02-16' '2023-02-17' '2023-02-18' '2023-02-19'
 '2023-02-20' '2023-02-21' '2023-02-22' '2023-02-23' '2023-02-24'
 '2023-02-25' '2023-02-26' '2023-02-27' '2023-02-28' '2023-03-01'
 '2023-03-02' '2023-03-03' '2023-03-04' '2023-03-05' '2023-03-06'
 '2023-03-07' '2023-03-08' '2023-03-09' '2023-03-10' '2023-03-11'
 '2023-03-12' '2023-03-13' '2023-03-14' '2023-03-15' '2023-03-16'
 '2023-03-17' '2023-03-18' '2023-03-19' '2023-03-20' '2023-03-21'
 '2023-03-22' '2023-03-23' '2023-03-24' '2023-03-25' '2023-03-26'
 '2023-03-27' '2023-03-28' '2023-03-29' '2023-03-30' '2023-03-31'
 '2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30'
 '2023-05-01' '2023-05-02' '2023-05-03' '2023-05-04' '2023-05-05'
 '2023-05-06' '2023-05-07' '2023-05-08' '2023-05-09' '2023-05-10'
 '2023-05-11' '2023-05-12' '2023-05-13' '2023-05-14' '2023-05-15'
 '2023-05-16' '2023-05-17' '2023-05-18' '2023-05-19' '2023-05-20'
 '2023-05-21' '2023-05-22' '2023-05-23' '2023-05-24' '2023-05-25'
 '2023-05-26' '2023-05-27' '2023-05-28' '2023-05-29' '2023-05-30'
 '2023-05-31' '2023-06-01' '2023-06-02' '2023-06-03' '2023-06-04'
 '2023-06-05' '2023-06-06' '2023-06-07' '2023-06-08' '2023-06-09'
 '2023-06-10' '2023-06-11' '2023-06-12' '2023-06-13' '2023-06-14'
 '2023-06-15' '2023-06-16' '2023-06-17' '2023-06-18' '2023-06-19'
 '2023-06-20' '2023-06-21' '2023-06-22' '2023-06-23' '2023-06-24'
 '2023-06-25' '2023-06-26' '2023-06-27' '2023-06-28' '2023-06-29'
 '2023-06-30' '2023-07-01' '2023-07-02' '2023-07-03' '2023-07-04'
 '2023-07-05' '2023-07-06' '2023-07-07' '2023-07-08' '2023-07-09'
 '2023-07-10' '2023-07-11' '2023-07-12' '2023-07-13' '2023-07-14'
 '2023-07-15' '2023-07-16' '2023-07-17' '2023-07-18' '2023-07-19'
 '2023-07-20' '2023-07-21' '2023-07-22' '2023-07-23' '2023-07-24'
 '2023-07-25' '2023-07-26' '2023-07-27' '2023-07-28' '2023-07-29'
 '2023-07-30' '2023-07-31' '2023-08-01' '2023-08-02' '2023-08-03'
 '2023-08-04' '2023-08-05' '2023-08-06' '2023-08-07' '2023-08-08'
 '2023-08-09' '2023-08-10' '2023-08-11' '2023-08-12' '2023-08-13'
 '2023-08-14' '2023-08-15' '2023-08-16' '2023-08-17' '2023-08-18'
 '2023-08-19' '2023-08-20' '2023-08-21' '2023-08-22' '2023-08-23'
 '2023-08-24' '2023-08-25' '2023-08-26' '2023-08-27' '2023-08-28'
 '2023-08-29' '2023-08-30' '2023-08-31' '2023-09-01' '2023-09-02'
 '2023-09-03' '2023-09-04' '2023-09-05' '2023-09-06' '2023-09-07'
 '2023-09-08' '2023-09-09' '2023-09-10' '2023-09-11' '2023-09-12'
 '2023-09-13' '2023-09-14' '2023-09-15' '2023-09-16' '2023-09-17'
 '2023-09-18' '2023-09-19' '2023-09-20' '2023-09-21' '2023-09-22'
 '2023-09-23' '2023-09-24' '2023-09-25' '2023-09-26' '2023-09-27'
 '2023-09-28' '2023-09-29' '2023-09-30' '2023-10-01' '2023-10-02'
 '2023-10-03' '2023-10-04' '2023-10-05' '2023-10-06' '2023-10-07'
 '2023-10-08' '2023-10-09' '2023-10-10' '2023-10-11' '2023-10-12'
 '2023-10-13' '2023-10-14' '2023-10-15' '2023-10-16' '2023-10-17'
 '2023-10-18' '2023-10-19' '2023-10-20' '2023-10-21' '2023-10-22'
 '2023-10-23' '2023-10-24' '2023-10-25' '2023-10-26' '2023-10-27'
 '2023-10-28' '2023-10-29' '2023-10-30' '2023-10-31' '2023-11-01'
 '2023-11-02' '2023-11-03' '2023-11-04' '2023-11-05' '2023-11-06'
 '2023-11-07' '2023-11-08' '2023-11-09' '2023-11-10' '2023-11-11'
 '2023-11-12' '2023-11-13' '2023-11-14' '2023-11-15' '2023-11-16'
 '2023-11-17' '2023-11-18' '2023-11-19' '2023-11-20' '2023-11-21'
 '2023-11-22' '2023-11-23' '2023-11-24' '2023-11-25' '2023-11-26'
 '2023-11-27' '2023-11-28' '2023-11-29' '2023-11-30' '2023-12-01'
 '2023-12-02' '2023-12-03' '2023-12-04' '2023-12-05' '2023-12-06'
 '2023-12-07' '2023-12-08' '2023-12-09' '2023-12-10' '2023-12-11'
 '2023-12-12' '2023-12-13' '2023-12-14' '2023-12-15' '2023-12-16'
 '2023-12-17' '2023-12-18' '2023-12-19' '2023-12-20' '2023-12-21'
 '2023-12-22' '2023-12-23' '2023-12-24' '2023-12-25' '2023-12-26'
 '2023-12-27' '2023-12-28' '2023-12-29' '2023-12-30' '2023-12-31']

# Genauere Blick auf SAP Rechnungen 2024

In [ ]:
# gibt es fehlende Werte in den Lieferantendaten
display(rechnungen_sap_2024.isna().sum())

Rechnungsnummer_SAP         0
Bestellnummer           28262
BelegDatum                  0
Beschreibung                0
Lieferant_Nummer            0
Sachkonto-Nummer        16294
Sachkonto-Name          17788
Buchungskreis-Nummer        0
Buchungskreis-Name          0
Material-Nummer         28262
Material-Name           28262
ECLASS-identifier           0
Menge                       0
Mengeneinheit           28262
Stückpreis              28262
Rechnungswert               0
Rechnungswährung            0
Zahlungsziel-Tage           0
Zahlungsbedingung           0
Zahlungsfrist               0
Zahlungsdatum               0
Rahmenvertrag           27259
dtype: int64

### Anpassen des Belegdatum von mm/tt/jjjj zu jjjj-mm-tt

In [ ]:
print(rechnungen_sap_2024["BelegDatum"].unique())

['01/01/2024' '01/02/2024' '01/03/2024' '01/04/2024' '01/05/2024'
 '01/06/2024' '01/07/2024' '01/08/2024' '01/09/2024' '01/10/2024'
 '01/11/2024' '01/12/2024' '01/13/2024' '01/14/2024' '01/15/2024'
 '01/16/2024' '01/17/2024' '01/18/2024' '01/19/2024' '01/20/2024'
 '01/21/2024' '01/22/2024' '01/23/2024' '01/24/2024' '01/25/2024'
 '01/26/2024' '01/27/2024' '01/28/2024' '01/29/2024' '01/30/2024'
 '01/31/2024' '02/01/2024' '02/02/2024' '02/03/2024' '02/04/2024'
 '02/05/2024' '02/06/2024' '02/07/2024' '02/08/2024' '02/09/2024'
 '02/10/2024' '02/11/2024' '02/12/2024' '02/13/2024' '02/14/2024'
 '02/15/2024' '02/16/2024' '02/17/2024' '02/18/2024' '02/19/2024'
 '02/20/2024' '02/21/2024' '02/22/2024' '02/23/2024' '02/24/2024'
 '02/25/2024' '02/26/2024' '02/27/2024' '02/28/2024' '03/01/2024'
 '03/02/2024' '03/03/2024' '03/04/2024' '03/05/2024' '03/06/2024'
 '03/07/2024' '03/08/2024' '03/09/2024' '03/10/2024' '03/11/2024'
 '03/12/2024' '03/13/2024' '03/14/2024' '03/15/2024' '03/16/2024'
 '03/17/2024' '03/18/2024' '03/19/2024' '03/20/2024' '03/21/2024'
 '03/22/2024' '03/23/2024' '03/24/2024' '03/25/2024' '03/26/2024'
 '03/27/2024' '03/28/2024' '03/29/2024' '03/30/2024' '03/31/2024'
 '04/01/2024' '04/02/2024' '04/03/2024' '04/04/2024' '04/05/2024'
 '04/06/2024' '04/07/2024' '04/08/2024' '04/09/2024' '04/10/2024'
 '04/11/2024' '04/12/2024' '04/13/2024' '04/14/2024' '04/15/2024'
 '04/16/2024' '04/17/2024' '04/18/2024' '04/19/2024' '04/20/2024'
 '04/21/2024' '04/22/2024' '04/23/2024' '04/24/2024' '04/25/2024'
 '04/26/2024' '04/27/2024' '04/28/2024' '04/29/2024' '04/30/2024'
 '05/01/2024' '05/02/2024' '05/03/2024' '05/04/2024' '05/05/2024'
 '05/06/2024' '05/07/2024' '05/08/2024' '05/09/2024' '05/10/2024'
 '05/11/2024' '05/12/2024' '05/13/2024' '05/14/2024' '05/15/2024'
 '05/16/2024' '05/17/2024' '05/18/2024' '05/19/2024' '05/20/2024'
 '05/21/2024' '05/22/2024' '05/23/2024' '05/24/2024' '05/25/2024'
 '05/26/2024' '05/27/2024' '05/28/2024' '05/29/2024' '05/30/2024'
 '05/31/2024' '06/01/2024' '06/02/2024' '06/03/2024' '06/04/2024'
 '06/05/2024' '06/06/2024' '06/07/2024' '06/08/2024' '06/09/2024'
 '06/10/2024' '06/11/2024' '06/12/2024' '06/13/2024' '06/14/2024'
 '06/15/2024' '06/16/2024' '06/17/2024' '06/18/2024' '06/19/2024'
 '06/20/2024' '06/21/2024' '06/22/2024' '06/23/2024' '06/24/2024'
 '06/25/2024' '06/26/2024' '06/27/2024' '06/28/2024' '06/29/2024'
 '06/30/2024' '07/01/2024' '07/02/2024' '07/03/2024' '07/04/2024'
 '07/05/2024' '07/06/2024' '07/07/2024' '07/08/2024' '07/09/2024'
 '07/10/2024' '07/11/2024' '07/12/2024' '07/13/2024' '07/14/2024'
 '07/15/2024' '07/16/2024' '07/17/2024' '07/18/2024' '07/19/2024'
 '07/20/2024' '07/21/2024' '07/22/2024' '07/23/2024' '07/24/2024'
 '07/25/2024' '07/26/2024' '07/27/2024' '07/28/2024' '07/29/2024'
 '07/30/2024' '07/31/2024' '08/01/2024' '08/02/2024' '08/03/2024'
 '08/04/2024' '08/05/2024' '08/06/2024' '08/07/2024' '08/08/2024'
 '08/09/2024' '08/10/2024' '08/11/2024' '08/12/2024' '08/13/2024'
 '08/14/2024' '08/15/2024' '08/16/2024' '08/17/2024' '08/18/2024'
 '08/19/2024' '08/20/2024' '08/21/2024' '08/22/2024' '08/23/2024'
 '08/24/2024' '08/25/2024' '08/26/2024' '08/27/2024' '08/28/2024'
 '08/29/2024' '08/30/2024' '08/31/2024' '09/01/2024' '09/02/2024'
 '09/03/2024' '09/04/2024' '09/05/2024' '09/06/2024' '09/07/2024'
 '09/08/2024' '09/09/2024' '09/10/2024' '09/11/2024' '09/12/2024'
 '09/13/2024' '09/14/2024' '09/15/2024' '09/16/2024' '09/17/2024'
 '09/18/2024' '09/19/2024' '09/20/2024' '09/21/2024' '09/22/2024'
 '09/23/2024' '09/24/2024' '09/25/2024' '09/26/2024' '09/27/2024'
 '09/28/2024' '09/29/2024' '09/30/2024' '10/01/2024' '10/02/2024'
 '10/03/2024' '10/04/2024' '10/05/2024' '10/06/2024' '10/07/2024'
 '10/08/2024' '10/09/2024' '10/10/2024' '10/11/2024' '10/12/2024'
 '10/13/2024' '10/14/2024' '10/15/2024' '10/16/2024' '10/17/2024'
 '10/18/2024' '10/19/2024' '10/20/2024' '10/21/2024' '10/22/2024'
 '10/23/2024' '10/24/2024' '10/25/2024' '10/26/2024' '10/27/2024'
 '10/28/2024' '10/29/2024' '10/30/2024' '10/31/2024' '11/01/2024'
 '11/02/2024' '11/03/2024' '11/04/2024' '11/05/2024' '11/06/2024'
 '11/07/2024' '11/08/2024' '11/09/2024' '11/10/2024' '11/11/2024'
 '11/12/2024' '11/13/2024' '11/14/2024' '11/15/2024' '11/16/2024'
 '11/17/2024' '11/18/2024' '11/19/2024' '11/20/2024' '11/21/2024'
 '11/22/2024' '11/23/2024' '11/24/2024' '11/25/2024' '11/26/2024'
 '11/27/2024' '11/28/2024' '11/29/2024' '11/30/2024' '12/01/2024'
 '12/02/2024' '12/03/2024' '12/04/2024' '12/05/2024' '12/06/2024'
 '12/07/2024' '12/08/2024' '12/09/2024' '12/10/2024' '12/11/2024'
 '12/12/2024' '12/13/2024' '12/14/2024' '12/15/2024' '12/16/2024'
 '12/17/2024' '12/18/2024' '12/19/2024' '12/20/2024' '12/21/2024'
 '12/22/2024' '12/23/2024' '12/24/2024' '12/25/2024' '12/26/2024'
 '12/27/2024' '12/28/2024' '12/29/2024' '12/30/2024']

In [ ]:
def datum_anpassen(df: pd.DataFrame, datum_spalte: str) -> pd.DataFrame:
    """
    Konvertiert die Werte in der angegebenen Datums-Spalte von mm/tt/jjjj zu jjjj-mm-tt

    Args:
        df (pd.DataFrame): Das DataFrame, das die Datums-Spalte enthält.
        datum_spalte (str): Der Name der Datums-Spalte, die konvertiert werden soll.

    Returns:
        pd.DataFrame: Das aktualisierte DataFrame mit der konvertierten Datums-Spalte.
    """
    df[datum_spalte] = pd.to_datetime(df[datum_spalte], format='%m/%d/%Y', errors='coerce')
    return df

In [ ]:
rechnungen_sap_2024_datum = datum_anpassen(rechnungen_sap_2024, "BelegDatum")

In [ ]:
display(rechnungen_sap_2024_datum[pd.isna(rechnungen_sap_2024_datum["BelegDatum"])].head())

Empty DataFrame
Columns: [Rechnungsnummer_SAP, Bestellnummer, BelegDatum, Beschreibung, Lieferant_Nummer, Sachkonto-Nummer, Sachkonto-Name, Buchungskreis-Nummer, Buchungskreis-Name, Material-Nummer, Material-Name, ECLASS-identifier, Menge, Mengeneinheit, Stückpreis, Rechnungswert, Rechnungswährung, Zahlungsziel-Tage, Zahlungsbedingung, Zahlungsfrist, Zahlungsdatum, Rahmenvertrag]
Index: []

### Lieferantenname hinzufügen

In [ ]:
rechnungen_sap_2024_datum_lieferantenname = merge_lieferanten_names(rechnungen_sap_2024_datum, lfa1_cleaned).rename(columns={'Name': 'Lieferantenname'})

In [ ]:
display(rechnungen_sap_2024_datum_lieferantenname.head())

,Rechnungsnummer_SAP,Bestellnummer,BelegDatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Rechnungswert,Rechnungswährung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname
0,R-19934029,NaN,2024-01-01,Papier weiß A3,L0318,SK_000002,NaN,3,Verwaltung Demo AG,NaN,NaN,24260604,1,NaN,NaN,1217.95,USD,30,30 Tage; 1% Skonto,2024-01-31,2024-01-28,NaN,Wasserleasing AG
1,R-20408868,NaN,2024-01-01,Zylinderschraube,L0028,NaN,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,23110000,1,NaN,NaN,592.38,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-02-11,NaN,Maschinenbau GmbH & Co. KG
2,R-53946015,NaN,2024-01-01,Zylinderschraube DIN,L0028,NaN,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,23110000,1,NaN,NaN,419.30,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-01-09,NaN,Maschinenbau GmbH & Co. KG
3,R-49696293,NaN,2024-01-01,"Test Runddrahtbürsten Ø x-mm Edelstdr. gew.,mm...",L0028,NaN,Maschinenteile und Ersatzte.,3,Verwaltung Demo AG,NaN,NaN,21190605,1,NaN,NaN,2804.05,USD,14,"14 Tage; 1,5% Skonto",2024-01-15,2024-01-09,NaN,Maschinenbau GmbH & Co. KG
4,R-45623784,NaN,2024-01-01,Gas Pauschale September,L0315,SK_000020,NaN,4,Auslandsgesellschaft SRO,NaN,NaN,26040201,1,NaN,NaN,34259.35,USD,30,30 Tage netto,2024-01-31,2024-01-26,V-27993028,Stadtwerke Bonn GmbH

### Überprüfen ob es auch fehlerhaft Daten gibt

In [ ]:
fehlerhafte_zeilen = rechnungen_sap_2024_datum_lieferantenname[
    rechnungen_sap_2024_datum_lieferantenname["Zahlungsdatum"] < rechnungen_sap_2024_datum_lieferantenname["BelegDatum"]
]

display(fehlerhafte_zeilen[["Zahlungsdatum", "BelegDatum", "Lieferant_Nummer", "Lieferantenname"]].sort_values(by="Zahlungsdatum").head(10))
print(f"Anzahl 'fehlerhafter' Zeilen: {len(fehlerhafte_zeilen)}")

    Zahlungsdatum BelegDatum Lieferant_Nummer               Lieferantenname
6      2023-12-26 2024-01-01            L0070   Honeywell Process Solutions
112    2023-12-27 2024-01-02            L0161          Reinigung Fassbender
169    2023-12-27 2024-01-02            L0193           Deutsche Post  GmbH
46     2023-12-28 2024-01-01            L0193           Deutsche Post  GmbH
344    2023-12-29 2024-01-04            L0071                IFM Elektronic
22     2023-12-29 2024-01-01            L0193           Deutsche Post  GmbH
53     2023-12-29 2024-01-01            L0189                 Deutsche Post
306    2023-12-29 2024-01-04            L0193           Deutsche Post  GmbH
148    2023-12-29 2024-01-02            L0189                 Deutsche Post
209    2023-12-30 2024-01-03            L0008                   Krupp+Essen

Anzahl 'fehlerhafter' Zeilen: 5279

In [ ]:
print(
    pd.to_datetime(
        rechnungen_sap_2024_datum_lieferantenname.Zahlungsdatum.unique()
    ).sort_values()
)

DatetimeIndex(['2023-12-26', '2023-12-27', '2023-12-28', '2023-12-29',
               '2023-12-30', '2023-12-31', '2024-01-01', '2024-01-02',
               '2024-01-03', '2024-01-04',
               ...
               '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
               '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
               '2024-12-30', '2024-12-31'],
              dtype='datetime64[ns]', length=372, freq=None)

### Wechselkurs den Rechnungen Df hinzufügen

In [ ]:
rechnungen_sap_2024_datum_lieferantenname_wechselkurs = add_wechselkurse_to_rechnungen(rechnungen_sap_2024_datum_lieferantenname, wechselkurse_df, "Rechnungswährung", "Zahlungsdatum")

In [ ]:
for i, (name, group) in enumerate(rechnungen_sap_2024_datum_lieferantenname_wechselkurs.groupby("Rechnungswährung")):
    print(f"\nGruppe: {name}")
    display(group[["Zahlungsdatum", "BelegDatum", "Lieferant_Nummer", "Lieferantenname", "Rechnungswert", "Rechnungswährung", "Wechselkurs"]].head(1))
    if i == 4:
        break

Gruppe: EUR

,Zahlungsdatum,BelegDatum,Lieferant_Nummer,Lieferantenname,Rechnungswert,Rechnungswährung,Wechselkurs
45,2024-01-02,2024-01-01,L0070,Honeywell Process Solutions,25762.56,EUR,1.0

Gruppe: GBP

,Zahlungsdatum,BelegDatum,Lieferant_Nummer,Lieferantenname,Rechnungswert,Rechnungswährung,Wechselkurs
28942,2024-12-23,2024-11-08,L0026,Robert Bosch GmbH,447.0,GBP,1.2049

Gruppe: USD

,Zahlungsdatum,BelegDatum,Lieferant_Nummer,Lieferantenname,Rechnungswert,Rechnungswährung,Wechselkurs
0,2024-01-28,2024-01-01,L0318,Wasserleasing AG,1217.95,USD,0.91988

In [ ]:
print(wechselkurse_df[wechselkurse_df["Datum"] == "2024-12-23"])
print(wechselkurse_df[wechselkurse_df["Datum"] == "2024-01-28"])

          Datum  Wechselkurs_USD  Wechselkurs_GBP
722  2024-12-23          0.96219           1.2049
          Datum  Wechselkurs_USD  Wechselkurs_GBP
392  2024-01-28          0.91988           1.1714

### Alle Rechnungen in Euro rechnen

In [ ]:
rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro = calc_spendeuro(rechnungen_sap_2024_datum_lieferantenname_wechselkurs, "Rechnungswert")

### Überprüfen der Sachkonto- nummer und name

In [ ]:
print(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro["Sachkonto-Nummer"].unique())
print(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro[["Sachkonto-Nummer", "Sachkonto-Name"]].drop_duplicates().sort_values(by="Sachkonto-Nummer"))

['SK_000002' nan 'SK_000020' 'SK_000008' 'SK_000001' 'SK_000009'
 'SK_000004' 'SK_000011' 'SK_000015' 'SK_000014' 'SK_000030' 'SK_000022'
 'SK_000005' 'SK_000019' 'SK_000007' 'SK_000016' 'SK_000029' 'SK_000021'
 'SK_000013']
     Sachkonto-Nummer                Sachkonto-Name
7           SK_000001                           NaN
0           SK_000002                           NaN
27          SK_000004                           NaN
92          SK_000005                           NaN
264         SK_000007                           NaN
5           SK_000008                           NaN
8           SK_000009                           NaN
31          SK_000011                           NaN
2115        SK_000013                           NaN
60          SK_000014                           NaN
43          SK_000015                           NaN
773         SK_000016                           NaN
198         SK_000019                           NaN
4           SK_000020                           NaN
1123        SK_000021                           NaN
74          SK_000022                           NaN
1036        SK_000029                           NaN
61          SK_000030                           NaN
1                 NaN  Maschinenteile und Ersatzte.

In [ ]:
print(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro["Sachkonto-Nummer"].unique())
print(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro[["Sachkonto-Nummer", "Sachkonto-Name"]].drop_duplicates().sort_values(by="Sachkonto-Nummer"))

['SK_000008' 'SK_000003' 'SK_000004' 'SK_000009' 'SK_000022' 'SK_000007'
 'SK_000005' 'SK_000020' 'SK_000002' 'SK_000001' 'SK_000030' 'SK_000014'
 'SK_000015' 'SK_000029' 'SK_000019' 'SK_000011' 'SK_000016' 'SK_000021'
 'SK_000013']
     Sachkonto-Nummer                         Sachkonto-Name
72          SK_000001                           Wareneinkauf
69          SK_000002  Verrechnung vorherige Buchungsperiode
1           SK_000003           Maschinenteile und Ersatzte.
2           SK_000004               Arbeitssicherheit, Ausr.
25          SK_000005               Aufwendungen für Gebäude
21          SK_000007                         Logistikbedarf
0           SK_000008                        Porto und Brief
7           SK_000009                               Logistik
556         SK_000011                 Arbeitsmittel Hardware
3335        SK_000013                   Außendienst Hardware
131         SK_000014                             KFZ-Kosten
185         SK_000015                       Dienstleistungen
750         SK_000016                   Mediendienstleistung
400         SK_000019                    Beratungsleistungen
55          SK_000020                                Energie
1657        SK_000021            Aufwendungen für Entsorgung
17          SK_000022               Reinigungsdienstleistung
234         SK_000029                               Lizenzen
78          SK_000030                             Bürobedarf

### Baue Sachkonto- nummer und Name Dict

In [ ]:
def sachkonto_dict(df: pd.DataFrame) -> dict:
    """
    Erstellt ein Dictionary aus Sachkonto-Nummer und Sachkonto-Name.

    Args:
        df (pd.DataFrame): DataFrame, das die Spalten 'Sachkonto-Nummer' und 'Sachkonto-Name' enthält.

    Returns:
        dict: Ein Dictionary mit Sachkonto-Nummer als Schlüssel und Sachkonto-Name als Wert.
    """
    return dict(zip(df['Sachkonto-Nummer'], df['Sachkonto-Name']))

In [ ]:
sachkonto_dict_2023 = sachkonto_dict(rechnungen_sap_2023)

In [ ]:
display(sachkonto_dict_2023)

{'SK_000008': 'Porto und Brief',
 'SK_000003': 'Maschinenteile und Ersatzte.',
 'SK_000004': 'Arbeitssicherheit, Ausr.',
 'SK_000009': 'Logistik',
 'SK_000022': 'Reinigungsdienstleistung',
 'SK_000007': 'Logistikbedarf',
 'SK_000005': 'Aufwendungen für Gebäude',
 'SK_000020': 'Energie',
 'SK_000001': 'Wareneinkauf',
 'SK_000002': 'Verrechnung vorherige Buchungsperiode',
 'SK_000030': 'Bürobedarf',
 'SK_000014': 'KFZ-Kosten',
 'SK_000015': 'Dienstleistungen',
 'SK_000029': 'Lizenzen',
 'SK_000019': 'Beratungsleistungen',
 'SK_000011': 'Arbeitsmittel Hardware',
 'SK_000016': 'Mediendienstleistung',
 'SK_000021': 'Aufwendungen für Entsorgung',
 'SK_000013': 'Außendienst Hardware'}

In [ ]:
display(reverse_dict := {v: k for k, v in sachkonto_dict_2023.items()})

{'Porto und Brief': 'SK_000008',
 'Maschinenteile und Ersatzte.': 'SK_000003',
 'Arbeitssicherheit, Ausr.': 'SK_000004',
 'Logistik': 'SK_000009',
 'Reinigungsdienstleistung': 'SK_000022',
 'Logistikbedarf': 'SK_000007',
 'Aufwendungen für Gebäude': 'SK_000005',
 'Energie': 'SK_000020',
 'Wareneinkauf': 'SK_000001',
 'Verrechnung vorherige Buchungsperiode': 'SK_000002',
 'Bürobedarf': 'SK_000030',
 'KFZ-Kosten': 'SK_000014',
 'Dienstleistungen': 'SK_000015',
 'Lizenzen': 'SK_000029',
 'Beratungsleistungen': 'SK_000019',
 'Arbeitsmittel Hardware': 'SK_000011',
 'Mediendienstleistung': 'SK_000016',
 'Aufwendungen für Entsorgung': 'SK_000021',
 'Außendienst Hardware': 'SK_000013'}

### Mappe die fehlenden Sachkonten in Rechungen SAP 2024 mit diesen Dict

In [ ]:
def sachkonto_mapping(df: pd.DataFrame, sachkonto_dict: dict, sachkonto_name: str, sachkonto_nummer: str) -> pd.DataFrame:
    """
    Mappt die Sachkonto-Nummern auf die Sachkonto-Namen basierend auf dem gegebenen Dictionary.

    Args:
        df (pd.DataFrame): DataFrame, das die Spalte 'Sachkonto-Nummer' enthält.
        sachkonto_dict (dict): Dictionary mit Sachkonto-Nummer als Schlüssel und Sachkonto-Name als Wert.
        sachkonto_name (str): Der Name der Spalte, die die Sachkonto-Namen enthält.
        sachkonto_nummer (str): Der Name der Spalte, die die Sachkonto-Nummern enthält.

    Returns:
        pd.DataFrame: DataFrame mit den aktualisierten Sachkonto-Nummern und -Namen.
    """

    reverse_dict = {v: k for k, v in sachkonto_dict.items()}

    df[sachkonto_name] = df[sachkonto_name].fillna(df[sachkonto_nummer].map(sachkonto_dict))
    df[sachkonto_nummer] = df[sachkonto_nummer].fillna(df[sachkonto_name].map(reverse_dict))

    return df

In [ ]:
rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto = sachkonto_mapping(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro, sachkonto_dict_2023, 'Sachkonto-Name', 'Sachkonto-Nummer')

In [ ]:
print(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto["Sachkonto-Nummer"].unique())
print(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto[["Sachkonto-Nummer", "Sachkonto-Name"]].drop_duplicates().sort_values(by="Sachkonto-Nummer"))

['SK_000002' 'SK_000003' 'SK_000020' 'SK_000008' 'SK_000001' 'SK_000009'
 'SK_000004' 'SK_000011' 'SK_000015' 'SK_000014' 'SK_000030' 'SK_000022'
 'SK_000005' 'SK_000019' 'SK_000007' 'SK_000016' 'SK_000029' 'SK_000021'
 'SK_000013']
     Sachkonto-Nummer                         Sachkonto-Name
7           SK_000001                           Wareneinkauf
0           SK_000002  Verrechnung vorherige Buchungsperiode
1           SK_000003           Maschinenteile und Ersatzte.
27          SK_000004               Arbeitssicherheit, Ausr.
92          SK_000005               Aufwendungen für Gebäude
264         SK_000007                         Logistikbedarf
5           SK_000008                        Porto und Brief
8           SK_000009                               Logistik
31          SK_000011                 Arbeitsmittel Hardware
2115        SK_000013                   Außendienst Hardware
60          SK_000014                             KFZ-Kosten
43          SK_000015                       Dienstleistungen
773         SK_000016                   Mediendienstleistung
198         SK_000019                    Beratungsleistungen
4           SK_000020                                Energie
1123        SK_000021            Aufwendungen für Entsorgung
74          SK_000022               Reinigungsdienstleistung
1036        SK_000029                               Lizenzen
61          SK_000030                             Bürobedarf

In [ ]:
display(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto.isna().sum())

Rechnungsnummer_SAP         0
Bestellnummer           28262
BelegDatum                  0
Beschreibung                0
Lieferant_Nummer            0
Sachkonto-Nummer            0
Sachkonto-Name              0
Buchungskreis-Nummer        0
Buchungskreis-Name          0
Material-Nummer         28262
Material-Name           28262
ECLASS-identifier           0
Menge                       0
Mengeneinheit           28262
Stückpreis              28262
Rechnungswert               0
Rechnungswährung            0
Zahlungsziel-Tage           0
Zahlungsbedingung           0
Zahlungsfrist               0
Zahlungsdatum               0
Rahmenvertrag           27259
Lieferantenname             0
Wechselkurs                 0
Spend_EUR                   0
dtype: int64

## Anpassen der Columnnames

In [ ]:
display(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto.columns)
display(rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro.columns)

Index(['Rechnungsnummer_SAP', 'Bestellnummer', 'BelegDatum', 'Beschreibung',
       'Lieferant_Nummer', 'Sachkonto-Nummer', 'Sachkonto-Name',
       'Buchungskreis-Nummer', 'Buchungskreis-Name', 'Material-Nummer',
       'Material-Name', 'ECLASS-identifier', 'Menge', 'Mengeneinheit',
       'Stückpreis', 'Rechnungswert', 'Rechnungswährung', 'Zahlungsziel-Tage',
       'Zahlungsbedingung', 'Zahlungsfrist', 'Zahlungsdatum', 'Rahmenvertrag',
       'Lieferantenname', 'Wechselkurs', 'Spend_EUR'],
      dtype='object')

Index(['Rechnungsnummer', 'Bestellnummer', 'Belegdatum', 'Beschreibung',
       'Lieferant_Nummer', 'Sachkonto-Nummer', 'Sachkonto-Name',
       'Buchungskreis-Nummer', 'Buchungskreis-Name', 'Material-Nummer',
       'Material-Name', 'ECLASS-identifier', 'Menge', 'Mengeneinheit',
       'Stückpreis', 'Spend', 'Währung', 'Zahlungsziel-Tage',
       'Zahlungsbedingung', 'Zahlungsfrist', 'Zahlungsdatum', 'Rahmenvertrag',
       'Lieferantenname', 'Wechselkurs', 'Spend_EUR'],
      dtype='object')

In [ ]:
def rename_columns(df: pd.DataFrame, column_mapping: dict) -> pd.DataFrame:
    """
    Bennennt die Spalten eines DataFrames um basierend auf einem gegebenen Mapping.

    Args:
        df (pd.DataFrame): Das DataFrame, dessen Spalten umbenannt werden sollen.
        column_mapping (dict): Ein Dictionary, das die alten Spaltennamen den neuen zuordnet.

    Returns:
        pd.DataFrame: Das DataFrame mit umbenannten Spalten.
    """
    return df.rename(columns=column_mapping)

In [ ]:
column_mapping = {
    'Rechnungsnummer_SAP': 'Rechnungsnummer',
    'BelegDatum': 'Belegdatum',
    'Rechnungswert': 'Spend',
    'Rechnungswährung': 'Währung'
}

In [ ]:
rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto_rename = rename_columns(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto, column_mapping)

In [ ]:
display(rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto_rename.columns)

Index(['Rechnungsnummer', 'Bestellnummer', 'Belegdatum', 'Beschreibung',
       'Lieferant_Nummer', 'Sachkonto-Nummer', 'Sachkonto-Name',
       'Buchungskreis-Nummer', 'Buchungskreis-Name', 'Material-Nummer',
       'Material-Name', 'ECLASS-identifier', 'Menge', 'Mengeneinheit',
       'Stückpreis', 'Spend', 'Währung', 'Zahlungsziel-Tage',
       'Zahlungsbedingung', 'Zahlungsfrist', 'Zahlungsdatum', 'Rahmenvertrag',
       'Lieferantenname', 'Wechselkurs', 'Spend_EUR'],
      dtype='object')

# Concat Rechungen 2023 und 2024

In [ ]:
rechnungen_2023_2024 = pd.concat([rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro, rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto_rename], ignore_index=True)

In [ ]:
display(rechnungen_2023_2024.head())

,Rechnungsnummer,Bestellnummer,Belegdatum,Beschreibung,Lieferant_Nummer,Sachkonto-Nummer,Sachkonto-Name,Buchungskreis-Nummer,Buchungskreis-Name,Material-Nummer,Material-Name,ECLASS-identifier,Menge,Mengeneinheit,Stückpreis,Spend,Währung,Zahlungsziel-Tage,Zahlungsbedingung,Zahlungsfrist,Zahlungsdatum,Rahmenvertrag,Lieferantenname,Wechselkurs,Spend_EUR
0,R-81402060,NaN,2023-01-01,Versand Kundenprämien,L0194,SK_000008,Porto und Brief,2,Vertriebsgesellschaft GmbH,NaN,NaN,14020000,1,NaN,NaN,683.40,EUR,14,14 Tage netto,2023-01-15,2023-01-09,NaN,Deutsche Post GmbH & Co.KG,1.0,683.40
1,R-60983007,NaN,2023-01-01,Zylinderschraube DIN,L0027,SK_000003,Maschinenteile und Ersatzte.,1,Produktion Bonn GmbH,NaN,NaN,23110000,1,NaN,NaN,211.53,EUR,30,30 Tage netto,2023-01-31,2023-02-10,V-74154614,ROBERT BOSCH,1.0,211.53
2,R-51330234,NaN,2023-01-01,Dummy Klaus Ludwig Leopard-Sicherheitsschuhe T...,L0097,SK_000004,"Arbeitssicherheit, Ausr.",2,Vertriebsgesellschaft GmbH,NaN,NaN,40250703,1,NaN,NaN,8655.51,EUR,30,30 Tage; 1% Skonto,2023-01-31,2023-01-25,NaN,Engelbert und Strauss,1.0,8655.51
3,R-62280354,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10937.30,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-11,NaN,Maschinenbau GmbH & Co. KG,1.0,10937.30
4,R-21995158,NaN,2023-01-01,SPIBO premium,L0028,SK_000003,Maschinenteile und Ersatzte.,4,Auslandsgesellschaft SRO,NaN,NaN,21182301,1,NaN,NaN,10991.05,EUR,14,"14 Tage; 1,5% Skonto",2023-01-15,2023-01-29,NaN,Maschinenbau GmbH & Co. KG,1.0,10991.05

In [ ]:
display(rechnungen_2023_2024.isna().sum())

Rechnungsnummer             0
Bestellnummer           56455
Belegdatum                  0
Beschreibung                0
Lieferant_Nummer            0
Sachkonto-Nummer            0
Sachkonto-Name              0
Buchungskreis-Nummer        0
Buchungskreis-Name          0
Material-Nummer         56455
Material-Name           56455
ECLASS-identifier           0
Menge                       0
Mengeneinheit           56455
Stückpreis              56455
Spend                       0
Währung                     0
Zahlungsziel-Tage           0
Zahlungsbedingung           0
Zahlungsfrist               0
Zahlungsdatum               0
Rahmenvertrag           54519
Lieferantenname             0
Wechselkurs                 0
Spend_EUR                   0
dtype: int64

# Save dfs to csv in /workspace/data/silver

In [ ]:
lfa1_cleaned.to_csv("/workspace/data/silver/LFA1_cleaned.csv", index=False, sep=";")
rechnungen_sap_2023_lieferantenname_valid_wechselkurs_spendeuro.to_csv("/workspace/data/silver/Rechnungen_SAP_2023.csv", index=False, sep=";")
rechnungen_sap_2024_datum_lieferantenname_wechselkurs_spendeuro_sachkonto_rename.to_csv("/workspace/data/silver/Rechnungen_SAP_2024.csv", index=False, sep=";")
rechnungen_2023_2024.to_csv("/workspace/data/silver/Rechnungen_SAP_2023_2024.csv", index=False, sep=";")